board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_new/', views.create, name='create'),
    path('<int:post_id>/post_detail', views.detail, name='detail'),
    path('<int:delete_post_id>/post_list', views.index, name="delete"),
    path('<int:post_id>/post_detail', views.update, name='update'),
]

board_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('board.urls')),
    path('admin/', admin.site.urls),
]

board/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

    def __str__(self):
        return self.title

board/models/comment.py
from django.db import models

from board.models import PostDetail


class Comment(models.Model):
    post_detail = models.ForeignKey(PostDetail, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()

board/models/post.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

board/models/post_detail.py
from django.db import models

from board.models import Post


class PostDetail(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="details")
    context = models.TextField()

board/views.py
# Create your views here.
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from board.models import PostDetail, Comment
from board.models.post import Post


def index(request, **kwargs):
    #delete post
    delete_post_id = kwargs.get('delete_post_id')
    if delete_post_id:
        delete_post = Post.objects.get(pk=delete_post_id)
        delete_post.delete()
    posts = Post.objects.all()
    page = request.GET.get('page', '1')
    paginator = Paginator(posts, '5')
    page_obj = paginator.page(page)
    return render(request, './post_list.html', {'page_obj': page_obj})


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        post = Post.objects.create(title=title)
        PostDetail.objects.create(post=post, context=content)
    return render(request, './create_new.html')


def detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    post_detail = PostDetail.objects.get(post=post)
    comment = ""
    if request.method == "POST":
        comment = request.POST.get('comment')
        title = request.POST.get('post_title')
        content = request.POST.get('post_detail_content')
        post.title = title
        post.save()
        post_detail.context = content
        post_detail.save()
    comment = comment
    if not comment == "":
        Comment.objects.create(post_detail=post_detail, comment=comment)
    comments = Comment.objects.filter(post_detail=post_detail)
    comment_count = comments.count()
    page = request.GET.get('page', '1')
    paginator = Paginator(comments, '3')
    page_comment = paginator.page(page)

    return render(request, './post_detail.html', {'post_detail': post_detail,
                                                  'page_comment': page_comment,
                                                  'comment_count': comment_count,
                                                  'post': post})


def update(request, **kwargs):
    print(1)
    print(post_id)
    post = Post.objects.get(pk=post_id)
    print(post)
    if request.method == "POST":
        print(000)
        title = request.POST.get('post_title')
        content = request.POST.get('post_detail_content')
        post.title = title
        post.save()
        print(111)
    print(222)
    return render(request, 'post_list.html')

templates/create_new.html
<!DOCTYPE html>
<html lang="en">
<form method ="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title"> title </label>
            <input type="text" class="form-control" id="id_title" name="title">
        </div>
        <div class="form-group">
            <lable for="id_content">content</lable>
            <textarea class="form-control" id="id_content" name="content" ></textarea>
        </div>
        <button type="submit" class="btn btn-success">submit</button>
        <a href="{% url 'index' %}">home</a>
</form>
</html>

templates/post_detail.html
<!DOCTYPE html>
<html>
<form method="POST">
    <ul style="text-align: center">
    <h1> here is the post_detail area</h1>
    <div style="height: 80px">
        <div style="font-size: x-large">
            title
        </div>
        <div>
        <textarea rows="1" cols="100" style="text-align: center" name="post_title">{{ post.title }}</textarea>
        </div>
    </div>
    <div>
        <div style="text-align: center; font-size: x-large">
            content
        </div>
        <div>
        <textarea rows="15" cols="100" style="text-align: center" name="post_detail_content">{{ post_detail.context }}</textarea>
        </div>
        <input type="submit" class="btndelete" value="save" style="height: 20px; width: 50px" onclick="location.href='/update/post_detail_id'">

    </div>

    <h2> here is the comment area in post_detail</h2>
        {% for comment in page_comment %}
            <div>
            <textarea rows="1" cols="100">{{ comment.comment }}</textarea>
            </div>
        {% endfor %}
        <!-- page list -->
    {% if comment_count == 0 %}
    {% else %}
        {% for page_number in page_comment.paginator.page_range %}
        {% if page_number == page_obj.number %}
            <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
        {% else %}
            <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
        {% endif %}
        {% endfor %}
    {% endif %}

    {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control" id="id_comment" name="comment" rows="1" cols="100"></textarea>
        </div>
            <button type="submit" class="btn btn-success">add comment</button>
    <a href="{% url 'index' %}">home</a>
    </ul>
</form>
</html>

templates/post_list.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/post_list.css' %}?after1">
</head>
        <h1 style="text-align: center; height: 100px; bottom:0" >Here is board main page </h1>
        {% for post in page_obj %}
        <table border="1" style="margin-left: auto; margin-right: auto; width: 1000px; height: 80px">
        <tr>
            <td width="40" style="text-align: center">1</td>
            <td width="800" style="text-align: center"><a href="{% url 'detail' post_id=post.id %}">
                {{ post.title }}</a></td>
            <td width="100" style="text-align: center"><a href="{% url 'delete' delete_post_id=post.id %}">
            <input type="button" class="btndelete" value="delete" id="id_delete" name="delete_post_id" style="height: 80px; width: 100px">
            </a></td>
        </tr>
        </table>
        {% endfor %}
        <div class="centered">
            <ul class="pagination justify-content-center">
            <!-- page list -->
            {% for page_number in page_obj.paginator.page_range %}
            {% if page_number == page_obj.number %}
                <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
            {% else %}
                <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
            {% endif %}
            {% endfor %}
            </ul>
            <a href="{% url 'create' %}" ><b><br><br><br>create</b></a>
        </div>

</html>